# Generated by Django 5.2.1 on 2025-05-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttag',
            name='icon',
            field=models.CharField(choices=[('fa-solid fa-bell', 'Bell'), ('fa-solid fa-envelope', 'Envelope'), ('fa-solid fa-check-circle', 'Check Circle'), ('fa-solid fa-exclamation-triangle', 'Exclamation Triangle'), ('fa-solid fa-info-circle', 'Info Circle'), ('fa-solid fa-times-circle', 'Times Circle'), ('fa-solid fa-user', 'User'), ('fa-solid fa-users', 'Users'), ('fa-solid fa-cog', 'Cog'), ('fa-solid fa-gear', 'Gear'), ('fa-solid fa-heart', 'Heart'), ('fa-solid fa-star', 'Star'), ('fa-solid fa-thumbs-up', 'Thumbs Up'), ('fa-solid fa-thumbs-down', 'Thumbs Down'), ('fa-solid fa-comment', 'Comment'), ('fa-solid fa-comments', 'Comments'), ('fa-solid fa-upload', 'Upload'), ('fa-solid fa-download', 'Download'), ('fa-solid fa-cloud-upload-alt', 'Cloud Upload'), ('fa-solid fa-cloud-download-alt', 'Cloud Download'), ('fa-solid fa-truck', 'Truck'), ('fa-solid fa-shipping-fast', 'Shipping Fast'), ('fa-solid fa-box', 'Box'), ('fa-solid fa-clipboard-check', 'Clipboard Check'), ('fa-solid fa-calendar', 'Calendar'), ('fa-solid fa-clock', 'Clock'), ('fa-solid fa-bug', 'Bug'), ('fa-solid fa-lock', 'Lock'), ('fa-solid fa-unlock', 'Unlock'), ('fa-solid fa-warning', 'Warning'), ('fa-solid fa-question-circle', 'Question Circle'), ('fa-solid fa-smile', 'Smile'), ('fa-solid fa-frown', 'Frown'), ('fa-solid fa-shopping-cart', 'Shopping Cart'), ('fa-solid fa-credit-card', 'Credit Card'), ('fa-solid fa-check', 'Check'), ('fa-solid fa-times', 'Times'), ('fa-solid fa-angle-double-right', 'Double Right Arrow'), ('fa-solid fa-angle-double-left', 'Double Left Arrow'), ('fa-solid fa-sync', 'Sync'), ('fa-solid fa-spinner', 'Spinner'), ('fa-solid fa-chart-line', 'Chart Line'), ('fa-solid fa-bolt', 'Bolt'), ('fa-solid fa-gift', 'Gift'), ('fa-solid fa-tag', 'Tag'), ('fa-solid fa-tags', 'Tags'), ('fa-solid fa-eye', 'Eye'), ('fa-solid fa-eye-slash', 'Eye Slash')], default='Heart', max_length=100),
        ),
    ]
