# Generated by Django 5.2.1 on 2025-05-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_posttag_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttag',
            name='icon',
            field=models.CharField(choices=[('fas fa-bell', 'Bell'), ('fas fa-envelope', 'Envelope'), ('fas fa-check-circle', 'Check Circle'), ('fas fa-exclamation-triangle', 'Exclamation Triangle'), ('fas fa-info-circle', 'Info Circle'), ('fas fa-times-circle', 'Times Circle'), ('fas fa-user', 'User'), ('fas fa-users', 'Users'), ('fas fa-cog', 'Cog'), ('fas fa-gear', 'Gear'), ('fas fa-heart', 'Heart'), ('fas fa-star', 'Star'), ('fas fa-thumbs-up', 'Thumbs Up'), ('fas fa-thumbs-down', 'Thumbs Down'), ('fas fa-comment', 'Comment'), ('fas fa-comments', 'Comments'), ('fas fa-upload', 'Upload'), ('fas fa-download', 'Download'), ('fas fa-cloud-upload-alt', 'Cloud Upload'), ('fas fa-cloud-download-alt', 'Cloud Download'), ('fas fa-truck', 'Truck'), ('fas fa-shipping-fast', 'Shipping Fast'), ('fas fa-box', 'Box'), ('fas fa-clipboard-check', 'Clipboard Check'), ('fas fa-calendar', 'Calendar'), ('fas fa-clock', 'Clock'), ('fas fa-bug', 'Bug'), ('fas fa-lock', 'Lock'), ('fas fa-unlock', 'Unlock'), ('fas fa-warning', 'Warning'), ('fas fa-question-circle', 'Question Circle'), ('fas fa-smile', 'Smile'), ('fas fa-frown', 'Frown'), ('fas fa-shopping-cart', 'Shopping Cart'), ('fas fa-credit-card', 'Credit Card'), ('fas fa-check', 'Check'), ('fas fa-times', 'Times'), ('fas fa-angle-double-right', 'Double Right Arrow'), ('fas fa-angle-double-left', 'Double Left Arrow'), ('fas fa-sync', 'Sync'), ('fas fa-spinner', 'Spinner'), ('fas fa-chart-line', 'Chart Line'), ('fas fa-bolt', 'Bolt'), ('fas fa-gift', 'Gift'), ('fas fa-tag', 'Tag'), ('fas fa-tags', 'Tags'), ('fas fa-eye', 'Eye'), ('fas fa-eye-slash', 'Eye Slash')], default='Tag', max_length=100),
        ),
    ]
